# Netlify Configuration File

# Build settings
[build]
  publish = "."

# Form handling - Redirect to thank-you page after submission
[[redirects]]
  from = "/thank-you"
  to = "/thank-you.html"
  status = 200
  force = true

# Handle form submissions with proper headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

# Specific caching for static assets
[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/media/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

# 404 page
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404